version: "3.9"

services:
  nextjs1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_WS_URL=ws://localhost:8081
      - INTERNAL_WS_URL=ws://ws-server1:8080
      - VOICEVOX_ENGINE_URL=${VOICEVOX_ENGINE_URL}
      - NEXT_PUBLIC_VRM_FILENAME=/Kiyoka_20241223143815.vrm
      - NEXT_PUBLIC_BG_IMAGE=/bg-d.png
    depends_on:
      - ws-server1

  ws-server1:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8081:8080"
    environment:
      - NODE_ENV=production
      - WS_PORT=8080
      - WS_HOST=0.0.0.0